export const IS_FETCHING = "IS_FETCHING";
export const SET_ERRORS = "SET_ERRORS";
export const SET_IN_EDIT = "SET_IN_EDIT";

export const MODELO_NIVEIS_SEARCH_RECEIVED = "MODELO_NIVEIS_SEARCH_RECEIVED";
export const MODELO_NIVEIS_SEARCH_FOREDIT_RECEIVED = "MODELO_NIVEIS_SEARCH_FOREDIT_RECEIVED";
export const MODELO_NIVEIS_GET_NEW = "MODELO_NIVEIS_GET_NEW";